module RDF
  class MODSRDF < RDF::Vocabulary("http://www.loc.gov/mods/modsrdf/v1#")
    #properties
    property :abstract
    property :accessCondition
    property :adminmetadata
    property :cartographics
    property :cartographicsCoodinates
    property :cartographicsProjection
    property :cartographicsScale
    property :classification
    property :classificationGroup
    property :classificationGroupScheme
    property :classificationGroupValue
    property :dateCaptured
    property :dateCapturedEnd
    property :dateCapturedStart
    property :dateCreated
    property :dateCreatedEnd
    property :dateCreatedStart
    property :dateModified
    property :dateModifiedEnd
    property :dateModifiedStart
    property :dateOfCopyright
    property :dateOfCopyrightEnd
    property :dateOfCopyrightStart
    property :dateValid
    property :dateValidEnd
    property :dateValidStart
    property :digitalOrigin
    property :edition
    property :frequency
    property :genre
    property :identifier
    property :identifierGroup
    property :identifierGroupType
    property :identifierGroupValue
    property :identifierValue
    property :issuance
    property :languageOfResource
    property :locationCopy
    property :locationCopyElectronicLocator
    property :locationCopyEnumerationAndChronology
    property :locationCopyEnumerationAndChronologyBasic
    property :locationCopyEnumerationAndChronologyIndex
    property :locationCopyEnumerationAndChronologySupplement
    property :locationCopyForm
    property :locationCopyNote
    property :locationCopyShelfLocator
    property :locationCopySublocation
    property :locationOfResource
    property :locationPhysical
    property :locationShelfLocator
    property :locationUrl
    property :mediaType
    property :name
    property :namePrincipal
    property :note
    property :noteGroup
    property :noteGroupType
    property :noteGroupValue
    property :part
    property :partDate
    property :partDetailType
    property :partEnd
    property :partLevel
    property :partList
    property :partName
    property :partNumber
    property :partOrder
    property :partStart
    property :partTotal
    property :partType
    property :partUnit
    property :physicalExtent
    property :physicalForm
    property :placeOfOrigin
    property :publisher
    property :recordContentSource
    property :recordDescriptionStandard
    property :recordIdentifier
    property :recordOrigin
    property :reformattingQuality
    property :relatedConstituent
    property :relatedFormat
    property :relatedHost
    property :relatedInstatiation
    property :relatedItem
    property :relatedOriginal
    property :relatedPreceding
    property :relatedReference
    property :relatedReferencedBy
    property :relatedReview
    property :relatedSeries
    property :relatedSucceeding
    property :relatedVersion
    property :role
    property :roleRelationship
    property :roleRelationshipName
    property :roleRelationshipRole
    property :statementOfResponsibility
    property :subject
    property :subjectComplex
    property :subjectGenre
    property :subjectGeographic
    property :subjectGeographicCode
    property :subjectHierarchicalGeographic
    property :subjectName
    property :subjectOccupation
    property :subjectTemporal
    property :subjectTitle
    property :subjectTemporal
    property :subjectTitle
    property :subjectTopic
    property :tableOfContents
    property :targetAudience
    property :title
    property :titlePrinciple
    property :titleUniform
  end
end
